name: CI

on: push

jobs:
  build:
    name: PharBuilder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout PharBuilder
        uses: actions/checkout@v2
        with:
          repository: NetherGamesMC/PharBuilder
          token: ${{ secrets.ng_token }}
          path: PharBuilder
          ref: php8
      - name: Download PHP Release
        uses: dsaltares/fetch-gh-release-asset@0.06
        with:
          file: Linux.zip
          repo: NetherGamesMC/php-build-scripts
          version: "tags/8.0"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unpack PHP Release
        run: unzip Linux.zip && tar -xzvf PHP_Linux-x86_64.tar.gz
      - name: Build
        run: |
          echo Building...
          chmod +x PharBuilder/PharBuilder.php
          ./bin/php7/bin/php -dphar.readonly=0 PharBuilder/PharBuilder.php --input . --out PharBuilder --stubs=PharBuilder/stubs
      - name: Upload
        uses: actions/upload-artifact@v2.2.4
        with:
          name: InvMenu
          path: PharBuilder/InvMenu.phar
