name: CI

on: push

jobs:
  build:
    name: PharBuilder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout PharBuilder
        uses: actions/checkout@v2
        with:
          repository: NetherGamesMC/PharBuilder
          token: ${{ secrets.ng_token }}
          path: PharBuilder
          ref: php8
      - name: Download PHP Release
        uses: dsaltares/fetch-gh-release-asset@0.0.5
        with:
          file: PHP_Linux.tar.gz
          repo: NetherGamesMC/php-build-scripts
          version: "tags/8.0.7"
      - name: Untar PHP Release
        run: tar -xzvf PHP_Linux.tar.gz
      - name: Build
        run: |
          echo Building...
          chmod +x PharBuilder/PharBuilder.php
          ./bin/php7/bin/php -dphar.readonly=0 PharBuilder/PharBuilder.php --input . --out PharBuilder --stubs=PharBuilder/stubs
      - name: Upload
        uses: actions/upload-artifact@v2.2.3
        with:
          name: InvMenu
          path: PharBuilder/InvMenu.phar
